### ISSUE TITLE
INTERSECT implementation failing

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/sequel-impala#15]
Though we are considering deprecating Intersect, among other operators (outcomesinsights/conceptql#78), I think there might be an issue with the implementation of INTERSECT in sequel-impala.  I think it has something to do with changes to the way columns are represented in Sequel.

```
 App 148 stdout: The AND operator requires at least 1 argument
 App 148 stdout: /home/app/bundle/gems/sequel-4.44.0/lib/sequel/sql.rb:239:in `initialize'
 App 148 stdout: /home/app/bundle/gems/sequel-4.44.0/lib/sequel/sql.rb:889:in `new'
 App 148 stdout: /home/app/bundle/gems/sequel-4.44.0/lib/sequel/sql.rb:889:in `&'
 App 148 stdout: /home/app/gems/sequel-impala/lib/sequel/adapters/shared/impala.rb:591:in `block in intersect'
 App 148 stdout: /home/app/bundle/gems/sequel-4.44.0/lib/sequel/dataset/query.rb:595:in `join_table'
 App 148 stdout: /home/app/gems/sequel-impala/lib/sequel/adapters/shared/impala.rb:511:in `join_table'
 App 148 stdout: /home/app/bundle/gems/sequel-4.44.0/lib/sequel/dataset/query.rb:608:in `inner_join'
 App 148 stdout: /home/app/bundle/gems/sequel-4.44.0/lib/sequel/dataset/query.rb:469:in `join'
 App 148 stdout: /home/app/gems/sequel-impala/lib/sequel/adapters/shared/impala.rb:591:in `intersect'
 App 148 stdout: /home/app/gems/conceptql/lib/conceptql/operators/intersect.rb:29:in `block (2 levels) in query'
 App 148 stdout: /home/app/gems/conceptql/lib/conceptql/operators/intersect.rb:24:in `each'
 App 148 stdout: /home/app/gems/conceptql/lib/conceptql/operators/intersect.rb:24:in `inject'
 App 148 stdout: /home/app/gems/conceptql/lib/conceptql/operators/intersect.rb:24:in `block in query'
 App 148 stdout: /home/app/gems/conceptql/lib/conceptql/operators/intersect.rb:23:in `each'
 App 148 stdout: /home/app/gems/conceptql/lib/conceptql/operators/intersect.rb:23:in `map'
 App 148 stdout: /home/app/gems/conceptql/lib/conceptql/operators/intersect.rb:23:in `query'
 App 148 stdout: /home/app/gems/conceptql/lib/conceptql/operators/operator.rb:196:in `evaluate'
 App 148 stdout: /home/app/gems/conceptql/lib/conceptql/query.rb:28:in `query'
 App 148 stdout: /home/app/gems/conceptql/lib/conceptql/query.rb:46:in `sql'
 App 148 stdout: /home/app/jam/app/services/translate_query.rb:21:in `sql'
 App 148 stdout: /home/app/jam/app/services/translate_query.rb:7:in `call'
 App 148 stdout: /home/app/jam/app/services/translate_queries.rb:25:in `translate'
 App 148 stdout: /home/app/jam/app/services/translate_queries.rb:21:in `block in result'
 App 148 stdout: /home/app/jam/app/services/translate_queries.rb:21:in `collect'
 App 148 stdout: /home/app/jam/app/services/translate_queries.rb:21:in `result'
 App 148 stdout: /home/app/jam/app/services/translate_queries.rb:10:in `call'
```

Looks like the culprit is this line: https://github.com/outcomesinsights/sequel-impala/blob/master/lib/sequel/adapters/shared/impala.rb#L591

**Comment by aguynamedryan** [comment]
I can't seem to recreate this now.  I'm going to close this ticket until I see this happen again.
